CREATE DATABASE LECTURE CHARSET 'UTF8' COLLATE 'utf8_unicode_ci'

USE LECTURE;

CREATE TABLE LECTURE 
(
	ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PASS MEDIUMTEXT NOT NULL,
    CLASS MEDIUMTEXT,
    
    PRIMARY KEY (ID)
)ENGINE InnoDB;

CREATE TABLE STUDENT
(
	ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PASS MEDIUMTEXT NOT NULL,
    
    PRIMARY KEY (ID)
)ENGINE InnoDB;

CREATE TABLE CLASS
(
	ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ROOM VARCHAR(100) NOT NULL,
    DATEBEGIN DATE NOT NULL,
    DATEEND DATE NOT NULL,
    HOURBEGIN TIME NOT NULL,
    HOUREND TIME NOT NULL,
    DAYMONTH TEXT NOT NULL,
    
    PRIMARY KEY(ID)
)ENGINE InnoDB;


INSERT INTO LECTURE
VALUES (111, 'LECTURE 1', '111', NULL), (112, 'LECTURE 2', '112', NULL), (113, 'LECTURE 3', '113', NULL);

INSERT INTO STUDENT
VALUES (111, 'STUDENT 1', '111'), (112, 'STUDENT 2', '112'), (113, 'STUDENT 3', '113');
